### ISSUE TITLE
VDL & ACARS frequencies are malformed

### ISSUE THREAD

**Issue by chrisglobe** [airframesio/acars-decoder-typescript#22]
- Example VDL via dumpvdl2: [https://app.airframes.io/messages/851426280](https://app.airframes.io/messages/851426280)
 - Example ACARS via acarsdec: [https://app.airframes.io/messages/851626168](https://app.airframes.io/messages/851626168)

In both cases, frequency is cut off after the decimal, so it shows `136` rather than `136.975` for example.

**Comment by makrsmark** [comment]
this seems to have been fixed at some point in time. frewquencies look good
