### ISSUE TITLE
Label 80 positions (lat/long) are scaled incorrectly.

### ISSUE THREAD

**Issue by fvance** [airframesio/acars-decoder-typescript#3]
Message ID 377573108.

The Lat and Long are decoded as: 293.95 N, 951.33 W

The actual values should be 29.395 N, 95.133 W.

The raw string is 
```
3N01 POSRPT 5891/04 KIAH/MMGL .XA-VOI
/POS N29395W095133/ALT +15608/MCH 558/FOB 0100/ETA 0410
```
The POS string is N29395W095133, which should be parsed as N 29.395, W 095.133

![Screenshot from 2022-08-03 21-24-53](https://user-images.githubusercontent.com/25825307/182750199-2e9681c1-a581-40b1-a963-0231dfdeb985.png)
.

**Comment by kevinelliott** [comment]
Great catch. I'll get this fixed.

**Comment by fvance** [comment]
Line 179 of lib/plugins/Label_80.ts, if I am reading this correctly.

Divisor should be 1000.

**Comment by kevinelliott** [comment]
If you feel up to it, you can edit the file here on GitHub and it'll submit a PR.

**Comment by fvance** [comment]
I am not confident of my diagnosis. Prefer you double check it this time.

**Comment by kevinelliott** [comment]
No problem, I can tackle!

**Comment by kevinelliott** [comment]
@makrsmark Another thing we can circle back to and review.

**Comment by makrsmark** [comment]
Looks like this is going to take a little work - Added 2 tests: variant 1 is this issue and variant 2 is a message that's decoded correctly. A simple fix (changing the scaling) for 1 breaks 2.

https://github.com/airframesio/acars-decoder-typescript/commit/df0a76c96301a4b6029558721a210aa9f8d0be4d

**Comment by kevinelliott** [comment]
> Looks like this is going to take a little work - Added 2 tests: variant 1 is this issue and variant 2 is a message that's decoded correctly. A simple fix (changing the scaling) for 1 breaks 2.
> 
> [df0a76c](https://github.com/airframesio/acars-decoder-typescript/commit/df0a76c96301a4b6029558721a210aa9f8d0be4d)

Halfway there 😆
